market_research:
  description: >
    调查今日头条上与该数字媒体账号所在行业相关的最新趋势、热门话题和竞争对手动态。重点关注哪些内容在当前年度表现良好,识别模式、偏好和新兴趋势。

    当前日期: {current_date}

    您正在进行研究的数字媒体账号描述:
    <DIGITAL_MEDIA_ACCOUNT_DESCRIPTION>{toutiao_description}</DIGITAL_MEDIA_ACCOUNT_DESCRIPTION>

    找出下周头条帖子最相关的话题、关键词和趋势。下周的重点内容是:
    <NEXT_WEEK_CONTENT>{topic_of_the_week}</NEXT_WEEK_CONTENT>

  expected_output: >
    一份报告,包含您发现的最相关信息,包括本周内容的最佳关键词和趋势,以及团队在内容创作中可能需要的所有其他信息。

content_strategy:
  description: >
    根据市场研究结果,制定一周的全面头条内容日历。日历应指定每周(从周一到周日)需要发布内容的主题,并提供帖子内容的初步想法。现在,请重点关注为期三天的内容日历,包括每个帖子中使用的最相关关键词和话题标签。
  expected_output: >
    一份详细的一周头条内容日历,采用 Markdown 格式,包括每周几天(从周一到周五)、内容创意概述,以及每个帖子中使用的最相关关键词和话题标签。确保日历与识别的趋势和受众偏好保持一致。

visual_content_creation:
  description: >
    根据每个头条帖子的内容策略,创作将在本周每天发布在头条上的视觉艺术。为此,您需要为每天使用的图像创建一个详细的描述。
    您使用的描述需要详细而简洁,应包括图像中应该存在的主要元素。描述颜色、物品、氛围以及您认为对于创建图像很重要的任何其他相关信息。
  expected_output: >
    一份 Markdown 文档,其中包含本周每个头条帖子将使用的图像的详细描述。 每个描述都应该简洁,包括主要元素、颜色、情绪以及任何其他指导图像创建的相关信息。 描述应与内容日历和已确定的趋势保持一致。
copywriting:
  description: >
    为本周每个头条帖子撰写富有吸引力和相关性的文案,与视觉内容相呼应,并遵循战略内容主题。文案应吸引受众,体现品牌声音,并鼓励互动。文案还应针对 SEO 优化,包含内容日历中包含的相关关键词和话题标签。

    以下是一些可用的文案示例:
    - "大家好!:heart: 我们很高兴与您分享我们的最新系列产品。请访问我们的网站了解更多详情。#新系列 #时尚 #风格"
    - "周一快乐!:sunflower: 用我们的美味果汁开启美好的一周吧。今天就来我们的店铺看看吧! #果汁 #健康生活 #周一动力"
    - "感到压力?:massage
  expected_output: >
    一份采用 Markdown 格式的文档,包含多个部分。每个部分应包含单个头条帖子的文案,以及相关的话题标签和号召行动。文案应富有吸引力,符合品牌风格,并与内容日历保持一致。

report_final_content_strategy:
  description: >
    编写一份全面的报告,概述本周的最终内容策略。该报告应包括市场研究结果、内容日历、每个帖子的文案以及 AI 生成的图像。提供策略的简要说明,解释其如何与识别的趋势和受众偏好保持一致。

  expected_output: >
    一份详细的报告,包括市场研究结果、内容日历、每个帖子的文案以及 AI 生成的图像。该报告应采用 Markdown 格式,并包括策略的简要说明,解释其如何与识别的趋势和受众偏好保持一致。 